### ISSUE TITLE
Cannot install in VS 2019 community

### ISSUE THREAD

**Issue by spocko** [cpmcgrath/UntabifyReplacement#9]
"This extension is not installable on any currently installed products"

Here's the log:
`6/17/2020 8:29:50 AM - Microsoft VSIX Installer
6/17/2020 8:29:50 AM - -------------------------------------------
6/17/2020 8:29:50 AM - vsixinstaller.exe version:
6/17/2020 8:29:50 AM - 16.6.2051
6/17/2020 8:29:50 AM - -------------------------------------------
6/17/2020 8:29:50 AM - Command line parameters:
6/17/2020 8:29:50 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\xxxxx\AppData\Local\Temp\UntabifyReplacement.vsix
6/17/2020 8:29:50 AM - -------------------------------------------
6/17/2020 8:29:50 AM - Microsoft VSIX Installer
6/17/2020 8:29:50 AM - -------------------------------------------
6/17/2020 8:29:50 AM - Initializing Install...
6/17/2020 8:29:50 AM - Extension Details...
6/17/2020 8:29:50 AM - 	Identifier         : UntabifyReplacement.CMcG.6897f9b0-a95a-4e02-88d5-46484a59ac9e
6/17/2020 8:29:50 AM - 	Name               : Untabify Replacement
6/17/2020 8:29:50 AM - 	Author             : Chris McGrath
6/17/2020 8:29:50 AM - 	Version            : 6.0.9.0
6/17/2020 8:29:50 AM - 	Description        : Replaces the Subpar Untabify in Visual Studio with one that replaces all tabs in the selected lines, not just those at the beginning.
6/17/2020 8:29:50 AM - 	Locale             : en-US
6/17/2020 8:29:50 AM - 	MoreInfoURL        : https://visualstudiogallery.msdn.microsoft.com/cc562125-6235-4082-b670-e0ed496b18a4
6/17/2020 8:29:50 AM - 	InstalledByMSI     : False
6/17/2020 8:29:50 AM - 	SupportedFrameworkVersionRange : [4.5,)
6/17/2020 8:29:50 AM - 
6/17/2020 8:29:50 AM - 	SignatureState     : Unsigned
6/17/2020 8:29:50 AM - 	Supported Products : 
6/17/2020 8:29:50 AM - 		Microsoft.VisualStudio.Community
6/17/2020 8:29:50 AM - 			Version : [11.0,16.0]
6/17/2020 8:29:50 AM - 		Microsoft.VisualStudio.Enterprise
6/17/2020 8:29:50 AM - 			Version : [11.0,16.0)
6/17/2020 8:29:50 AM - 		Microsoft.VisualStudio.Pro
6/17/2020 8:29:50 AM - 			Version : [11.0,16.0)
6/17/2020 8:29:50 AM - 		Microsoft.VisualStudio.Premium
6/17/2020 8:29:50 AM - 			Version : [11.0,16.0)
6/17/2020 8:29:50 AM - 		Microsoft.VisualStudio.Ultimate
6/17/2020 8:29:50 AM - 			Version : [11.0,16.0)
6/17/2020 8:29:50 AM - 
6/17/2020 8:29:50 AM - 	References         : 
6/17/2020 8:29:50 AM - 		-------------------------------------------------------
6/17/2020 8:29:50 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
6/17/2020 8:29:50 AM - 		Name         : Visual Studio MPF 11.0
6/17/2020 8:29:50 AM - 		Version      : [11.0,)
6/17/2020 8:29:50 AM - 		MoreInfoURL  : 
6/17/2020 8:29:50 AM - 		Nested       : No
6/17/2020 8:29:50 AM - 
6/17/2020 8:29:50 AM - 	Prerequisites      : 
6/17/2020 8:29:50 AM - 		-------------------------------------------------------
6/17/2020 8:29:50 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/17/2020 8:29:50 AM - 		Name         : Visual Studio core editor
6/17/2020 8:29:50 AM - 		Version      : [15.0,)
6/17/2020 8:29:50 AM - 
6/17/2020 8:29:50 AM - Signature Details...
6/17/2020 8:29:50 AM - 	Extension is not signed.
6/17/2020 8:29:50 AM - 
6/17/2020 8:29:50 AM - Searching for applicable products...
6/17/2020 8:29:50 AM - Found installed product - Global Location
6/17/2020 8:29:50 AM - Found installed product - Visual Studio Community 2019
6/17/2020 8:29:50 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
`

**Comment by spocko** [comment]
Probably needs the same fix as was done here:
https://github.com/cpmcgrath/TrimLineEnds/pull/9

**Comment by michaelm7456** [comment]
Hi @cpmcgrath, is it possible to have this [Pull Request](https://github.com/cpmcgrath/UntabifyReplacement/pull/10) reviewed and merged if the changes meet your approval?

And for the latest iteration of the Repo to be published on the '**Visual Studio Marketplace**' once you have time?

Many thanks for the excellent Extension!
